name: online_book_reading_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  http: ^1.1.0
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/svgs/
  fonts:
    - family: Readex Pro
      fonts:
        - asset: assets/fonts/ReadexPro-VariableFont_HEXP,wght.ttf
  uses-material-design: true
